#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_Etudiants.View.Etudiant
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Gestion_Etudiant")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Définitions de méthodes d'extensibilité
    partial void OnCreated();
    partial void Insertetudiants(etudiants instance);
    partial void Updateetudiants(etudiants instance);
    partial void Deleteetudiants(etudiants instance);
    partial void Insertfilieres(filieres instance);
    partial void Updatefilieres(filieres instance);
    partial void Deletefilieres(filieres instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::Gestion_Etudiants.Properties.Settings.Default.Gestion_EtudiantConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<etudiants> etudiants
		{
			get
			{
				return this.GetTable<etudiants>();
			}
		}
		
		public System.Data.Linq.Table<filieres> filieres
		{
			get
			{
				return this.GetTable<filieres>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.etudiants")]
	public partial class etudiants : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _CNE;
		
		private string _Nom;
		
		private string _Prenom;
		
		private string _email;
		
		private string _Sexe;
		
		private System.Nullable<System.DateTime> _DateNaissance;
		
		private string _Addresse;
		
		private string _Phone;
		
		private System.Nullable<int> _FiliereId;
		
		private EntityRef<filieres> _filieres;
		
		private EntityRef<filieres> _filieres1;
		
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCNEChanging(string value);
    partial void OnCNEChanged();
    partial void OnNomChanging(string value);
    partial void OnNomChanged();
    partial void OnPrenomChanging(string value);
    partial void OnPrenomChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnSexeChanging(string value);
    partial void OnSexeChanged();
    partial void OnDateNaissanceChanging(System.Nullable<System.DateTime> value);
    partial void OnDateNaissanceChanged();
    partial void OnAddresseChanging(string value);
    partial void OnAddresseChanged();
    partial void OnPhoneChanging(string value);
    partial void OnPhoneChanged();
    partial void OnFiliereIdChanging(System.Nullable<int> value);
    partial void OnFiliereIdChanged();
    #endregion
		
		public etudiants()
		{
			this._filieres = default(EntityRef<filieres>);
			this._filieres1 = default(EntityRef<filieres>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CNE", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string CNE
		{
			get
			{
				return this._CNE;
			}
			set
			{
				if ((this._CNE != value))
				{
					this.OnCNEChanging(value);
					this.SendPropertyChanging();
					this._CNE = value;
					this.SendPropertyChanged("CNE");
					this.OnCNEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nom", DbType="VarChar(50)")]
		public string Nom
		{
			get
			{
				return this._Nom;
			}
			set
			{
				if ((this._Nom != value))
				{
					this.OnNomChanging(value);
					this.SendPropertyChanging();
					this._Nom = value;
					this.SendPropertyChanged("Nom");
					this.OnNomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Prenom", DbType="VarChar(50)")]
		public string Prenom
		{
			get
			{
				return this._Prenom;
			}
			set
			{
				if ((this._Prenom != value))
				{
					this.OnPrenomChanging(value);
					this.SendPropertyChanging();
					this._Prenom = value;
					this.SendPropertyChanged("Prenom");
					this.OnPrenomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(100)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sexe", DbType="VarChar(10)")]
		public string Sexe
		{
			get
			{
				return this._Sexe;
			}
			set
			{
				if ((this._Sexe != value))
				{
					this.OnSexeChanging(value);
					this.SendPropertyChanging();
					this._Sexe = value;
					this.SendPropertyChanged("Sexe");
					this.OnSexeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateNaissance", DbType="Date")]
		public System.Nullable<System.DateTime> DateNaissance
		{
			get
			{
				return this._DateNaissance;
			}
			set
			{
				if ((this._DateNaissance != value))
				{
					this.OnDateNaissanceChanging(value);
					this.SendPropertyChanging();
					this._DateNaissance = value;
					this.SendPropertyChanged("DateNaissance");
					this.OnDateNaissanceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Addresse", DbType="VarChar(100)")]
		public string Addresse
		{
			get
			{
				return this._Addresse;
			}
			set
			{
				if ((this._Addresse != value))
				{
					this.OnAddresseChanging(value);
					this.SendPropertyChanging();
					this._Addresse = value;
					this.SendPropertyChanged("Addresse");
					this.OnAddresseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phone", DbType="VarChar(20)")]
		public string Phone
		{
			get
			{
				return this._Phone;
			}
			set
			{
				if ((this._Phone != value))
				{
					this.OnPhoneChanging(value);
					this.SendPropertyChanging();
					this._Phone = value;
					this.SendPropertyChanged("Phone");
					this.OnPhoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FiliereId", DbType="Int")]
		public System.Nullable<int> FiliereId
		{
			get
			{
				return this._FiliereId;
			}
			set
			{
				if ((this._FiliereId != value))
				{
					if ((this._filieres.HasLoadedOrAssignedValue || this._filieres1.HasLoadedOrAssignedValue))
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnFiliereIdChanging(value);
					this.SendPropertyChanging();
					this._FiliereId = value;
					this.SendPropertyChanged("FiliereId");
					this.OnFiliereIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="filieres_etudiants", Storage="_filieres", ThisKey="FiliereId", OtherKey="filiereId", IsForeignKey=true)]
		public filieres filieres
		{
			get
			{
				return this._filieres.Entity;
			}
			set
			{
				filieres previousValue = this._filieres.Entity;
				if (((previousValue != value) 
							|| (this._filieres.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._filieres.Entity = null;
						previousValue.etudiants.Remove(this);
					}
					this._filieres.Entity = value;
					if ((value != null))
					{
						value.etudiants.Add(this);
						this._FiliereId = value.filiereId;
					}
					else
					{
						this._FiliereId = default(Nullable<int>);
					}
					this.SendPropertyChanged("filieres");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="filieres_etudiants1", Storage="_filieres1", ThisKey="FiliereId", OtherKey="filiereId", IsForeignKey=true, DeleteRule="CASCADE")]
		public filieres filieres1
		{
			get
			{
				return this._filieres1.Entity;
			}
			set
			{
				filieres previousValue = this._filieres1.Entity;
				if (((previousValue != value) 
							|| (this._filieres1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._filieres1.Entity = null;
						previousValue.etudiants1.Remove(this);
					}
					this._filieres1.Entity = value;
					if ((value != null))
					{
						value.etudiants1.Add(this);
						this._FiliereId = value.filiereId;
					}
					else
					{
						this._FiliereId = default(Nullable<int>);
					}
					this.SendPropertyChanged("filieres1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.filieres")]
	public partial class filieres : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _filiereId;
		
		private string _Nom;
		
		private EntitySet<etudiants> _etudiants;
		
		private EntitySet<etudiants> _etudiants1;
		
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnfiliereIdChanging(int value);
    partial void OnfiliereIdChanged();
    partial void OnNomChanging(string value);
    partial void OnNomChanged();
    #endregion
		
		public filieres()
		{
			this._etudiants = new EntitySet<etudiants>(new Action<etudiants>(this.attach_etudiants), new Action<etudiants>(this.detach_etudiants));
			this._etudiants1 = new EntitySet<etudiants>(new Action<etudiants>(this.attach_etudiants1), new Action<etudiants>(this.detach_etudiants1));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_filiereId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int filiereId
		{
			get
			{
				return this._filiereId;
			}
			set
			{
				if ((this._filiereId != value))
				{
					this.OnfiliereIdChanging(value);
					this.SendPropertyChanging();
					this._filiereId = value;
					this.SendPropertyChanged("filiereId");
					this.OnfiliereIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nom", DbType="VarChar(200)")]
		public string Nom
		{
			get
			{
				return this._Nom;
			}
			set
			{
				if ((this._Nom != value))
				{
					this.OnNomChanging(value);
					this.SendPropertyChanging();
					this._Nom = value;
					this.SendPropertyChanged("Nom");
					this.OnNomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="filieres_etudiants", Storage="_etudiants", ThisKey="filiereId", OtherKey="FiliereId")]
		public EntitySet<etudiants> etudiants
		{
			get
			{
				return this._etudiants;
			}
			set
			{
				this._etudiants.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="filieres_etudiants1", Storage="_etudiants1", ThisKey="filiereId", OtherKey="FiliereId")]
		public EntitySet<etudiants> etudiants1
		{
			get
			{
				return this._etudiants1;
			}
			set
			{
				this._etudiants1.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_etudiants(etudiants entity)
		{
			this.SendPropertyChanging();
			entity.filieres = this;
		}
		
		private void detach_etudiants(etudiants entity)
		{
			this.SendPropertyChanging();
			entity.filieres = null;
		}
		
		private void attach_etudiants1(etudiants entity)
		{
			this.SendPropertyChanging();
			entity.filieres1 = this;
		}
		
		private void detach_etudiants1(etudiants entity)
		{
			this.SendPropertyChanging();
			entity.filieres1 = null;
		}
	}
}
#pragma warning restore 1591
